### ISSUE TITLE
installing issue

### ISSUE THREAD

**Issue by Popx1** [SingularisArt/Singularis#1]
Singularis-master! ❯ ./install --aspect "dotfiles(^bin)"                     0.00s [main●] ~/Downloads/Singularis-master
[Notice]   Installing my Dotfiles.
[Info]     Installed .xprofile.
[Info]     Installed .zshenv.
[Info]     Installed GeoGebra.
[Info]     Installed awesome.
[Info]     Installed bashtop.
[Info]     Installed bottom.
[Info]     Installed bspwm.
[Info]     Installed btop.
[Info]     Installed calcurse.
[Info]     Installed castero.
[Info]     Installed chameleon.
[Info]     Installed cmus.
[Info]     Installed cointop.
[Info]     Installed dunst.
[Info]     Installed dwm.
[Info]     Installed easytag.
[Info]     Installed git.
[Info]     Installed gtk-2.0.
[Info]     Installed gtk-3.0.
[Info]     Installed gtk-4.0.
[Info]     Installed inkscape.
[Info]     Installed inkscape-figures.
[Info]     Installed ipython.
[Info]     Installed kitty.
[Info]     Installed lf.
[Info]     Installed lynx.
[Info]     Installed manuskript.
[Info]     Installed mpd.
[Info]     Installed mpv.
[Info]     Installed ncmpcpp.
[Info]     Installed neofetch.
[Info]     Installed newsboat.
[Info]     Installed picom.
[Info]     Installed polybar.
[Info]     Installed python.
[Info]     Installed ranger.
[Info]     Installed rofi.
[Info]     Installed sioyek.
[Info]     Installed sxhkd.
[Info]     Installed tmux.
[Info]     Installed wal.
[Info]     Installed wal-discord.
[Info]     Installed zsh.
[Info]     Installed fehbg.
[Warn]     Skipping the installation of bin.
[Warn]     You need to be using the --singularis command to install the share aspect.
Traceback (most recent call last):
  File "/home/lahcen/Downloads/Singularis-master/./install", line 5, in <module>
    main.main()
  File "/home/lahcen/Downloads/Singularis-master/man/main.py", line 207, in main
    parse_arguments(args)
  File "/home/lahcen/Downloads/Singularis-master/man/main.py", line 38, in parse_arguments
    core(args)
  File "/home/lahcen/Downloads/Singularis-master/man/main.py", line 13, in core
    [aspect.install_aspect() for aspect in aspects["aspects_to_install"]]
  File "/home/lahcen/Downloads/Singularis-master/man/main.py", line 13, in <listcomp>
    [aspect.install_aspect() for aspect in aspects["aspects_to_install"]]
     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lahcen/Downloads/Singularis-master/man/operations/aspects.py", line 54, in install_aspect
    exec(code, replace_vars)
  File "<string>", line 15, in <module>
  File "/home/lahcen/Downloads/Singularis-master/man/operations/template.py", line 189, in __init__
    dict.__init__(self, self.get_templates())
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/lahcen/Downloads/Singularis-master/man/operations/template.py", line 205, in get_templates
    Template(
  File "/home/lahcen/Downloads/Singularis-master/man/operations/template.py", line 68, in __init__
    self.setup_for_installation()
  File "/home/lahcen/Downloads/Singularis-master/man/operations/template.py", line 92, in setup_for_installation
    self.install()
  File "/home/lahcen/Downloads/Singularis-master/man/operations/template.py", line 123, in install
    private_vars = yaml.load(private_info, Loader=yaml.FullLoader)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/lib/python3.11/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/lib/python3.11/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/lib/python3.11/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 15: invalid start byte

**Comment by Popx1** [comment]
i need your help i do not know how to fix this its the smae even when installing bin and using sudo

**Comment by SingularisArt** [comment]
I'll look into it over the next few days or so, as I've got finals coming back.

**Comment by Popx1** [comment]
Am still wating.

**Comment by SingularisArt** [comment]
Alright. It should work now.

**Comment by Popx1** [comment]
I can't test it but i will close the issue

**Comment by Popx1** [comment]
⋊> ~/Downloads cd Singularis-master/                                            15:32:28
aspects       CONTRIBUTING.md  LICENSE.md  pyrightconfig.json  unsafe-permissions.sh
CHANGELOG.md  install          man         README.md
⋊> ~/Downloads/Singularis-master install -c                                     15:32:31
install: missing file operand
Try 'install --help' for more information.
⋊> ~/Downloads/Singularis-master ./install -c                                   15:32:43
[Notice]   Installing my Systemd Files.
[Info]     Installed systemd.
[Warn]     No python libraries to install for systemd.
[Warn]     No node libraries to install for systemd.
[Success]  Installed my Systemd Files.
[Notice]   Installing my NeoVim configuration.
[Info]     Installed nvim.
[Error]    Error installing python library neovim for Nvim.
[Error]    Error installing python library latex2sympy2 for Nvim.
[Error]    Error installing python library pyright for Nvim.
[Error]    Error installing python library python-language-server[all] for Nvim.
[Error]    Error installing python library black for Nvim.
[Error]    Error installing python library jedi for Nvim.
[Error]    Error installing python library yamllint for Nvim.
[Warn]     No node libraries to install for nvim.
[Success]  Installed my NeoVim configuration.
[Notice]   Installing my Email Setup.
[Info]     Installed abook.
[Info]     Installed gcalcli.
[Info]     Installed glow.
[Info]     Installed goobook.
[Info]     Installed imapfilter.
[Info]     Installed khal.
[Info]     Installed khard.
[Info]     Installed neomutt.
[Info]     Installed vdirsyncer.
[Warn]     No python libraries to install for email.
[Warn]     No node libraries to install for email.
[Success]  Installed my Email Setup.
[Notice]   Installing my Dotfiles.
[Info]     Installed .xprofile.
[Info]     Installed .zshenv.
[Info]     Installed GeoGebra.
[Info]     Installed awesome.
[Info]     Installed bashtop.
[Info]     Installed bottom.
[Info]     Installed bspwm.
[Info]     Installed btop.
[Info]     Installed calcurse.
[Info]     Installed castero.
[Info]     Installed chameleon.
[Info]     Installed cmus.
[Info]     Installed cointop.
[Info]     Installed dunst.
[Info]     Installed dwm.
[Info]     Installed easytag.
[Info]     Installed git.
[Info]     Installed gtk-2.0.
[Info]     Installed gtk-3.0.
[Info]     Installed gtk-4.0.
[Info]     Installed inkscape.
[Info]     Installed inkscape-figures.
[Info]     Installed ipython.
[Info]     Installed kitty.
[Info]     Installed lf.
[Info]     Installed lynx.
[Info]     Installed manuskript.
[Info]     Installed mpd.
[Info]     Installed mpv.
[Info]     Installed ncmpcpp.
[Info]     Installed neofetch.
[Info]     Installed newsboat.
[Info]     Installed picom.
[Info]     Installed polybar.
[Info]     Installed python.
[Info]     Installed ranger.
[Info]     Installed rofi.
[Info]     Installed sioyek.
[Info]     Installed sxhkd.
[Info]     Installed tmux.
[Info]     Installed wal.
[Info]     Installed wal-discord.
[Info]     Installed zsh.
[Info]     Installed fehbg.
Traceback (most recent call last):
  File "/home/lahcen/Downloads/Singularis-master/./install", line 5, in <module>
    main.main()
  File "/home/lahcen/Downloads/Singularis-master/man/main.py", line 207, in main
    parse_arguments(args)
  File "/home/lahcen/Downloads/Singularis-master/man/main.py", line 38, in parse_arguments
    core(args)
  File "/home/lahcen/Downloads/Singularis-master/man/main.py", line 13, in core
    [aspect.install_aspect() for aspect in aspects["aspects_to_install"]]
  File "/home/lahcen/Downloads/Singularis-master/man/main.py", line 13, in <listcomp>
    [aspect.install_aspect() for aspect in aspects["aspects_to_install"]]
     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lahcen/Downloads/Singularis-master/man/operations/aspects.py", line 54, in install_aspect
    exec(code, replace_vars)
  File "<string>", line 15, in <module>
  File "/home/lahcen/Downloads/Singularis-master/man/operations/file.py", line 155, in __init__
    self.get_files()
  File "/home/lahcen/Downloads/Singularis-master/man/operations/file.py", line 176, in get_files
    File(
  File "/home/lahcen/Downloads/Singularis-master/man/operations/file.py", line 31, in __init__
    self.setup_for_installation()
  File "/home/lahcen/Downloads/Singularis-master/man/operations/file.py", line 54, in setup_for_installation
    self.install()
  File "/home/lahcen/Downloads/Singularis-master/man/operations/file.py", line 117, in install
    helpers.symlink(file_location, file_destination)
  File "/home/lahcen/Downloads/Singularis-master/man/helpers.py", line 27, in symlink
    os.makedirs(os.path.dirname(destination), exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: '/home/lahcen/.local/bin'


More issues

**Comment by Popx1** [comment]
Its saying installed but its not installed

**Comment by SingularisArt** [comment]
For the last issue, you just need to create the ~/.local/bin folder. I'll add that in the code, but try again after creating and add the `--log 2` parameter to see what exactly is making pip fail to install those packages. Here's the full installation line: `./install --all --log 2`.

**Comment by Popx1** [comment]
Here is what i got
```
Singularis-master ❯ ./install --all --log 2                                                                                             0.00s ~/Downloads/Singularis-master
[Notice]   Installing my Systemd Files.
[Info]     Installed systemd.
[Warn]     No python libraries to install for systemd.
[Warn]     No node libraries to install for systemd.
[Success]  Installed my Systemd Files.
[Notice]   Installing my NeoVim configuration.
[Info]     Installed nvim.
[Error]    Error installing python library neovim for Nvim.
[Error]    Error installing python library latex2sympy2 for Nvim.
[Error]    Error installing python library pyright for Nvim.
[Error]    Error installing python library python-language-server[all] for Nvim.
[Error]    Error installing python library black for Nvim.
[Error]    Error installing python library jedi for Nvim.
[Error]    Error installing python library yamllint for Nvim.
[Warn]     No node libraries to install for nvim.
[Success]  Installed my NeoVim configuration.
[Notice]   Installing my Email Setup.
[Info]     Installed abook.
[Info]     Installed gcalcli.
[Info]     Installed glow.
[Info]     Installed goobook.
[Info]     Installed imapfilter.
[Info]     Installed khal.
[Info]     Installed khard.
[Info]     Installed neomutt.
[Info]     Installed vdirsyncer.
[Warn]     No python libraries to install for email.
[Warn]     No node libraries to install for email.
[Success]  Installed my Email Setup.
[Notice]   Installing my Dotfiles.
[Info]     Installed .xprofile.
[Info]     Installed .zshenv.
[Info]     Installed GeoGebra.
[Info]     Installed awesome.
[Info]     Installed bashtop.
[Info]     Installed bottom.
[Info]     Installed bspwm.
[Info]     Installed btop.
[Info]     Installed calcurse.
[Info]     Installed castero.
[Info]     Installed chameleon.
[Info]     Installed cmus.
[Info]     Installed cointop.
[Info]     Installed dunst.
[Info]     Installed dwm.
[Info]     Installed easytag.
[Info]     Installed git.
[Info]     Installed gtk-2.0.
[Info]     Installed gtk-3.0.
[Info]     Installed gtk-4.0.
[Info]     Installed inkscape.
[Info]     Installed inkscape-figures.
[Info]     Installed ipython.
[Info]     Installed kitty.
[Info]     Installed lf.
[Info]     Installed lynx.
[Info]     Installed manuskript.
[Info]     Installed mpd.
[Info]     Installed mpv.
[Info]     Installed ncmpcpp.
[Info]     Installed neofetch.
[Info]     Installed newsboat.
[Info]     Installed picom.
[Info]     Installed polybar.
[Info]     Installed python.
[Info]     Installed ranger.
[Info]     Installed rofi.
[Info]     Installed sioyek.
[Info]     Installed sxhkd.
[Info]     Installed tmux.
[Info]     Installed wal.
[Info]     Installed wal-discord.
[Info]     Installed zsh.
[Info]     Installed fehbg.
Traceback (most recent call last):
  File "/home/lahcen/Downloads/Singularis-master/./install", line 5, in <module>
    main.main()
  File "/home/lahcen/Downloads/Singularis-master/man/main.py", line 207, in main
    parse_arguments(args)
  File "/home/lahcen/Downloads/Singularis-master/man/main.py", line 38, in parse_arguments
    core(args)
  File "/home/lahcen/Downloads/Singularis-master/man/main.py", line 13, in core
    [aspect.install_aspect() for aspect in aspects["aspects_to_install"]]
     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lahcen/Downloads/Singularis-master/man/operations/aspects.py", line 54, in install_aspect
    exec(code, replace_vars)
  File "<string>", line 15, in <module>
  File "/home/lahcen/Downloads/Singularis-master/man/operations/file.py", line 155, in __init__
    self.get_files()
  File "/home/lahcen/Downloads/Singularis-master/man/operations/file.py", line 176, in get_files
    File(
  File "/home/lahcen/Downloads/Singularis-master/man/operations/file.py", line 31, in __init__
    self.setup_for_installation()
  File "/home/lahcen/Downloads/Singularis-master/man/operations/file.py", line 54, in setup_for_installation
    self.install()
  File "/home/lahcen/Downloads/Singularis-master/man/operations/file.py", line 117, in install
    helpers.symlink(file_location, file_destination)
  File "/home/lahcen/Downloads/Singularis-master/man/helpers.py", line 27, in symlink
    os.makedirs(os.path.dirname(destination), exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: '/home/lahcen/.local/bin'
```

**Comment by Popx1** [comment]
> For the last issue, you just need to create the ~/.local/bin folder. I'll add that in the code, but try again after creating and add the `--log 2` parameter to see what exactly is making pip fail to install those packages. Here's the full installation line: `./install --all --log 2`.

There is ~/.local/bin folder
